# Generated by Django 3.0.3 on 2020-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='premises',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='events_image',
            field=models.ImageField(default='img/default.jpg', upload_to='img/'),
        ),
    ]
