# Generated by Django 3.0.3 on 2020-02-22 15:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200222_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='events_image',
            field=models.ImageField(default=main.models.random_img, upload_to='img/'),
        ),
    ]
