# Generated by Django 3.0.3 on 2020-02-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200222_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-events_holding_date'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
