# Generated by Django 3.0.2 on 2020-02-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200224_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
