# Generated by Django 3.0.3 on 2020-02-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200224_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
