# Generated by Django 3.0.2 on 2020-02-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200224_2055'),
        ('main', '0010_auto_20200224_2121'),
    ]

    operations = [
    ]
