# Generated by Django 3.0.3 on 2020-02-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200225_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
